#!/bin/bash

post_install() {
	 /bin/cp -rf usr/lib/seamonkey-2.7/defaults/profile/localstore.rdf{.sxt,}
}

post_upgrade() {
	 /bin/cp -rf usr/lib/seamonkey-2.7/defaults/profile/localstore.rdf{.sxt,}

	 # clean_old_files
	 for ver in 2.5 2.6 2.6.1; do
		  shopt -s nullglob
		  rm -f usr/lib/seamonkey-${ver}/defaults/profile/localstore.rdf.*
		  rmdir --ignore-fail-on-non-empty -p usr/lib/seamonkey-${ver}/ &>/dev/null; :
	 done
}
