#!/bin/bash

ver_sm=2.16
pastvers=(2.5 2.6 2.6.1 2.7 2.7.1 2.7.2 2.8 2.9 2.10 2.11 2.12.1 2.13 2.13.1 2.13.2 2.14 2.14.1 2.15.1 2.15.2)

post_install() {
	 /bin/cp -rf usr/lib/seamonkey-$ver_sm/defaults/profile/localstore.rdf{.sxt,}
}

post_upgrade() {
	 /bin/cp -rf usr/lib/seamonkey-$ver_sm/defaults/profile/localstore.rdf{.sxt,}

	 # clean_old_files
	 for ver in "${pastvers[@]}"; do
		  shopt -s nullglob
		  rm -f usr/lib/seamonkey-${ver}/defaults/profile/localstore.rdf.*
		  rmdir --ignore-fail-on-non-empty -p usr/lib/seamonkey-${ver}/defaults/profile/ &>/dev/null; :
	 done
}
