#!/usr/bin/bash
#
# updates a zip file from stdin
#
# USAGE: cat new_file_contents | rezip zipfile.zip internal/path/to/new_file

for arg; do
	 [ -a "$arg" ] && unzip -qqt "$arg" &>/dev/null && {
		  zipfile="$arg"
		  continue
	 }
	 [[ "$arg" =~ \.\./ ]] && continue
	 zpath=$arg
done

[ "$zipfile" ] && [ "$zpath" ] || exit 1

while :; do
	 td=/tmp/.rezip.$EUID.$$.$(date +%s).$RANDOM
	 mkdir -p $td && break
done
pushd $td &>/dev/null
trap "popd &>/dev/null; rm -rf $td; exit;" EXIT HUP QUIT INT TERM ABRT TSTP CONT

#stuff inside tmpdir

cp "$zipfile" $td/tmp.zip
mkdir -p $td/"$(dirname "$zpath")"
cat <&0 >| $td/"$zpath"
zip -qf tmp.zip "$zpath"
mv -f $td/tmp.zip "$zipfile"
